ALTER TABLE "Story"
  ADD COLUMN "captionFont" VARCHAR(16) NOT NULL DEFAULT 'MODERN',
  ADD COLUMN "captionSize" VARCHAR(12) NOT NULL DEFAULT 'MEDIUM',
  ADD COLUMN "captionAlign" VARCHAR(12) NOT NULL DEFAULT 'CENTER',
  ADD COLUMN "captionBold" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN "captionItalic" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "captionColor" VARCHAR(16) NOT NULL DEFAULT '#ffffff',
  ADD COLUMN "captionBg" VARCHAR(16) NOT NULL DEFAULT 'NONE',
  ADD COLUMN "captionBgColor" VARCHAR(16) NOT NULL DEFAULT '#171922';
