ALTER TABLE "Story"
ADD COLUMN "captionPosition" VARCHAR(12) NOT NULL DEFAULT 'BOTTOM',
ADD COLUMN "captionOffsetX" DOUBLE PRECISION NOT NULL DEFAULT 50,
ADD COLUMN "captionOffsetY" DOUBLE PRECISION NOT NULL DEFAULT 82,
ADD COLUMN "captionRotation" INTEGER NOT NULL DEFAULT 0;
