ALTER TABLE "User"
ADD COLUMN "gender" TEXT,
ADD COLUMN "workplace" TEXT,
ADD COLUMN "interests" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "socialLinks" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
