ALTER TABLE "Story"
ADD COLUMN "backgroundColorA" VARCHAR(16) NOT NULL DEFAULT '#4b3d36',
ADD COLUMN "backgroundColorB" VARCHAR(16) NOT NULL DEFAULT '#766052',
ADD COLUMN "backgroundColorC" VARCHAR(16) NOT NULL DEFAULT '#b3927c';
