ALTER TABLE "Story"
  ADD COLUMN "mediaScale" DOUBLE PRECISION NOT NULL DEFAULT 1,
  ADD COLUMN "mediaRotation" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "mediaFlipX" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "mediaFlipY" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "mediaOffsetX" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN "mediaOffsetY" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN "mediaFit" VARCHAR(12) NOT NULL DEFAULT 'COVER',
  ADD COLUMN "mediaFrame" VARCHAR(16) NOT NULL DEFAULT 'PORTRAIT';
